# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"count_tags": "00_helper.ipynb",
         "evaluate": "00_helper.ipynb"}

modules = ["helper.py"]

doc_url = "https://MANOHMU3.github.io/spacyhelper/"

git_url = "https://github.com/MANOHMU3/spacyhelper/tree/master/"

def custom_doc_links(name): return None
