# AUTOGENERATED! DO NOT EDIT! File to edit: 00_helper.ipynb (unless otherwise specified).

__all__ = ['count_tags']

# Cell
def count_tags(spacy_data):
    ents_count = dict()
    for instance in spacy_data:
        ents = instance[1]['entities']
        for ent in ents: ents_count[ent[2]] = ents_count.get(ent[2], 0) + 1
    return ents_count